# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8510ed915e597239f4ef1253539d884ff58f8ccf699d32dd689dc14120130b6a6b69080bfe74e1022bcb3f6d630e0a6c08fa8286acae8256b809987a4c8747c8

test:
  secret_key_base: ed98efcc6dca5c3214551294a429d0c4544d23c984d613953878bfaac4c3ac130e97f7e25c11913366ffee56d0e5d56d4e6f9b0e75abb59981b04b072b79242a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
